services:
  - type: web
    name: metabase
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_HOST
        value: dpg-d1bftrur433s739j3g60-a.oregon-postgres.render.com
      - key: MB_DB_PORT
        value: 5432
      - key: MB_DB_DBNAME
        value: bdosce
      - key: MB_DB_USER
        value: bdosce_user
      - key: MB_DB_PASS
        value: WU6oQRnomZgct27EyMn3WzWsX10IxyvM
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx384m
    ports:
      - port: 3000
        protocol: tcp
